// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3KNGz6N5iYheasa8R-1JJl2NpPfzZ5DQ',
    appId: '1:17280252449:web:47fe734d5e2af37cf78160',
    messagingSenderId: '17280252449',
    projectId: 'productmanagement-fe02a',
    authDomain: 'productmanagement-fe02a.firebaseapp.com',
    storageBucket: 'productmanagement-fe02a.appspot.com',
    measurementId: 'G-KV4HYJFFT6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAllnOLC7N0fRBtQMBD9Bl1mBbwKRml_uk',
    appId: '1:17280252449:android:624bb57868aa1d45f78160',
    messagingSenderId: '17280252449',
    projectId: 'productmanagement-fe02a',
    storageBucket: 'productmanagement-fe02a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnO5k0Cb0wEUdoPdlPCoMOjzgCfchglDI',
    appId: '1:17280252449:ios:e25d4217d9b7556cf78160',
    messagingSenderId: '17280252449',
    projectId: 'productmanagement-fe02a',
    storageBucket: 'productmanagement-fe02a.appspot.com',
    iosBundleId: 'com.example.productmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnO5k0Cb0wEUdoPdlPCoMOjzgCfchglDI',
    appId: '1:17280252449:ios:e25d4217d9b7556cf78160',
    messagingSenderId: '17280252449',
    projectId: 'productmanagement-fe02a',
    storageBucket: 'productmanagement-fe02a.appspot.com',
    iosBundleId: 'com.example.productmanagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3KNGz6N5iYheasa8R-1JJl2NpPfzZ5DQ',
    appId: '1:17280252449:web:8f9002a33163f96ff78160',
    messagingSenderId: '17280252449',
    projectId: 'productmanagement-fe02a',
    authDomain: 'productmanagement-fe02a.firebaseapp.com',
    storageBucket: 'productmanagement-fe02a.appspot.com',
    measurementId: 'G-GTL9LMRZCC',
  );
}
